// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ODataBatching8.Models
{
    [Table("Book")]
    public partial class Book
    {
        public Book()
        {
            BooksInGroups = new HashSet<BooksInGroup>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [Column("ISBN")]
        [StringLength(30)]
        public string Isbn { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        [Required]
        [StringLength(50)]
        public string Author { get; set; }
        [Column(TypeName = "money")]
        public decimal Price { get; set; }
        public Guid AddressId { get; set; }
        public Guid PressId { get; set; }

        [ForeignKey(nameof(AddressId))]
        [InverseProperty("Books")]
        public virtual Address Address { get; set; }
        [ForeignKey(nameof(PressId))]
        [InverseProperty("Books")]
        public virtual Press Press { get; set; }
        [InverseProperty(nameof(BooksInGroup.Book))]
        public virtual ICollection<BooksInGroup> BooksInGroups { get; set; }
    }
}