// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ODataBatching8.Models
{
    public partial class Field
    {
        public Field()
        {
            UserFieldAccesses = new HashSet<UserFieldAccess>();
        }

        [Key]
        public Guid Id { get; set; }
        public Guid TableId { get; set; }
        [Required]
        public string FieldName { get; set; }
        [Required]
        public string FieldDataType { get; set; }
        public string FieldProperties { get; set; }
        [Column("fieldOrder")]
        public int FieldOrder { get; set; }

        [ForeignKey(nameof(TableId))]
        [InverseProperty("Fields")]
        public virtual Table Table { get; set; }
        [InverseProperty(nameof(UserFieldAccess.Field))]
        public virtual ICollection<UserFieldAccess> UserFieldAccesses { get; set; }
    }
}