// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ODataBatching8.Models
{
    public partial class Groups
    {
        public Groups()
        {
            BooksInGroups = new HashSet<BooksInGroups>();
            UsersInGroup = new HashSet<UsersInGroup>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string GroupName { get; set; }

        [InverseProperty("Group")]
        public virtual ICollection<BooksInGroups> BooksInGroups { get; set; }
        [InverseProperty("Group")]
        public virtual ICollection<UsersInGroup> UsersInGroup { get; set; }
    }
}