// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ODataBatching8.Models
{
    public partial class Group
    {
        public Group()
        {
            BooksInGroups = new HashSet<BooksInGroup>();
            UsersInGroups = new HashSet<UsersInGroup>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string GroupName { get; set; }

        [InverseProperty(nameof(BooksInGroup.Group))]
        public virtual ICollection<BooksInGroup> BooksInGroups { get; set; }
        [InverseProperty(nameof(UsersInGroup.Group))]
        public virtual ICollection<UsersInGroup> UsersInGroups { get; set; }
    }
}