// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ODataBatching8.Models
{
    [Table("Press")]
    public partial class Press
    {
        public Press()
        {
            Books = new HashSet<Book>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(150)]
        public string Email { get; set; }
        public int Category { get; set; }

        [InverseProperty(nameof(Book.Press))]
        public virtual ICollection<Book> Books { get; set; }
    }
}