// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ODataBatching8.Models
{
    public partial class Table
    {
        public Table()
        {
            Fields = new HashSet<Field>();
            UserTableAccesses = new HashSet<UserTableAccess>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        public string TableName { get; set; }
        [Required]
        public string ControllerName { get; set; }

        [InverseProperty(nameof(Field.Table))]
        public virtual ICollection<Field> Fields { get; set; }
        [InverseProperty(nameof(UserTableAccess.Table))]
        public virtual ICollection<UserTableAccess> UserTableAccesses { get; set; }
    }
}