// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ODataBatching8.Models
{
    [Table("UsersInGroup")]
    public partial class UsersInGroup
    {
        [Key]
        public Guid UserId { get; set; }
        [Key]
        public Guid GroupId { get; set; }

        [ForeignKey(nameof(GroupId))]
        [InverseProperty("UsersInGroups")]
        public virtual Group Group { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("UsersInGroups")]
        public virtual User User { get; set; }
    }
}