// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ODataBatching8.Models
{
    [Table("UserTableAccess")]
    public partial class UserTableAccess
    {
        [Key]
        public Guid Id { get; set; }
        public Guid UserId { get; set; }
        public Guid TableId { get; set; }
        public int TableAccessLevel { get; set; }

        [ForeignKey(nameof(TableId))]
        [InverseProperty("UserTableAccesses")]
        public virtual Table Table { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserTableAccesses")]
        public virtual User User { get; set; }
    }
}