// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ODataBatching8.Models
{
    [Keyless]
    public partial class UserAccessView
    {
        public Guid Id { get; set; }
        [Required]
        [StringLength(255)]
        public string UserName { get; set; }
        [Required]
        public string TableName { get; set; }
        public int TableAccessLevel { get; set; }
        [Required]
        public string FieldName { get; set; }
        public int FieldLevelAccess { get; set; }
        [Required]
        public string FieldDataType { get; set; }
        public string FieldProperties { get; set; }
        [Column("fieldOrder")]
        public int FieldOrder { get; set; }
        [Required]
        public string ControllerName { get; set; }
    }
}