// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace ODataBatching8.Models
{
    public partial class User
    {
        public User()
        {
            UsersInGroups = new HashSet<UsersInGroup>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(255)]
        public string UserName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastLogin { get; set; }
        [Column("status")]
        public int? Status { get; set; }

        [InverseProperty(nameof(UsersInGroup.User))]
        public virtual ICollection<UsersInGroup> UsersInGroups { get; set; }
    }
}