// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    public partial class ApplicationRequest
    {
        public ApplicationRequest()
        {
            ApplicationPermissionGroups = new HashSet<ApplicationPermissionGroup>();
        }

        [Key]
        public Guid Id { get; set; }
        public string PrivateApiKey { get; set; }
        public string ReviewFeedback { get; set; }
        public int Status { get; set; }
        public DateTime RequestDate { get; set; }
        public Guid OrganizationId { get; set; }
        public Guid RequestedSystemDetailsId { get; set; }
        public DateTime RequestProdDate { get; set; }
        public string RequestType { get; set; }
        public byte[] EdmModel { get; set; }
        public DateTime EdmModelUpdateDate { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty("ApplicationRequests")]
        public virtual Organization Organization { get; set; }
        [ForeignKey(nameof(RequestedSystemDetailsId))]
        [InverseProperty(nameof(RequestedSystemDetail.ApplicationRequests))]
        public virtual RequestedSystemDetail RequestedSystemDetails { get; set; }
        [InverseProperty(nameof(ApplicationPermissionGroup.ApplicationRequest))]
        public virtual ICollection<ApplicationPermissionGroup> ApplicationPermissionGroups { get; set; }
    }
}