// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    public partial class ApplicationPermissionGroup
    {
        [Key]
        public Guid Id { get; set; }
        public Guid ApplicationRequestId { get; set; }
        public Guid PermissionGroupId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        [ForeignKey(nameof(ApplicationRequestId))]
        [InverseProperty("ApplicationPermissionGroups")]
        public virtual ApplicationRequest ApplicationRequest { get; set; }
        [ForeignKey(nameof(PermissionGroupId))]
        [InverseProperty("ApplicationPermissionGroups")]
        public virtual PermissionGroup PermissionGroup { get; set; }
    }
}