// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    [Table("E920TableFields")]
    public partial class E920tableFields
    {
        public E920tableFields()
        {
            PermissionGroupE920tableFields = new HashSet<PermissionGroupE920tableFields>();
        }

        [Key]
        public Guid Id { get; set; }
        [Column("E920TableId")]
        public Guid E920tableId { get; set; }
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        [ForeignKey(nameof(E920tableId))]
        [InverseProperty(nameof(E920tables.E920tableFields))]
        public virtual E920tables E920table { get; set; }
        [InverseProperty("E920tableField")]
        public virtual ICollection<PermissionGroupE920tableFields> PermissionGroupE920tableFields { get; set; }
    }
}