// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    [Table("E920Apis")]
    public partial class E920apis
    {
        [Key]
        public Guid Id { get; set; }
        public string ApiName { get; set; }
        public string ServerName { get; set; }
        public string ServerIpAddress { get; set; }
        public string LogLevelEndpoint { get; set; }
        public bool IsLocal { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    }
}