// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    [Table("E920Tables")]
    public partial class E920tables
    {
        public E920tables()
        {
            E920tableFields = new HashSet<E920tableFields>();
            PermissionGroupE920tables = new HashSet<PermissionGroupE920tables>();
        }

        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        [InverseProperty("E920table")]
        public virtual ICollection<E920tableFields> E920tableFields { get; set; }
        [InverseProperty("E920table")]
        public virtual ICollection<PermissionGroupE920tables> PermissionGroupE920tables { get; set; }
    }
}