// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    [Table("E920Claims")]
    public partial class E920claims
    {
        public E920claims()
        {
            OrganizationClaims = new HashSet<OrganizationClaim>();
        }

        [Key]
        public Guid Id { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string ClaimType { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string ClaimTable { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string ClaimColumn { get; set; }

        [InverseProperty(nameof(OrganizationClaim.Claim))]
        public virtual ICollection<OrganizationClaim> OrganizationClaims { get; set; }
    }
}