// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    public partial class OrganizationClaim
    {
        [Key]
        public Guid Id { get; set; }
        public Guid OrganizationId { get; set; }
        public Guid ClaimId { get; set; }

        [ForeignKey(nameof(ClaimId))]
        [InverseProperty(nameof(E920claims.OrganizationClaims))]
        public virtual E920claims Claim { get; set; }
        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty("OrganizationClaims")]
        public virtual Organization Organization { get; set; }
    }
}