// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    public partial class Organization
    {
        public Organization()
        {
            ApplicationRequests = new HashSet<ApplicationRequest>();
            OrganizationClaims = new HashSet<OrganizationClaim>();
        }

        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string OfficeSymbol { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        [InverseProperty(nameof(ApplicationRequest.Organization))]
        public virtual ICollection<ApplicationRequest> ApplicationRequests { get; set; }
        [InverseProperty(nameof(OrganizationClaim.Organization))]
        public virtual ICollection<OrganizationClaim> OrganizationClaims { get; set; }
    }
}