// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    public partial class PermissionGroup
    {
        public PermissionGroup()
        {
            ApplicationPermissionGroups = new HashSet<ApplicationPermissionGroup>();
            PermissionGroupE920tables = new HashSet<PermissionGroupE920tables>();
        }

        [Key]
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public bool Active { get; set; }
        public bool Private { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        [InverseProperty(nameof(ApplicationPermissionGroup.PermissionGroup))]
        public virtual ICollection<ApplicationPermissionGroup> ApplicationPermissionGroups { get; set; }
        [InverseProperty("PermissionGroup")]
        public virtual ICollection<PermissionGroupE920tables> PermissionGroupE920tables { get; set; }
    }
}