// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    [Table("PermissionGroupE920TableFields")]
    public partial class PermissionGroupE920tableFields
    {
        [Key]
        public Guid Id { get; set; }
        public bool Get { get; set; }
        public bool Post { get; set; }
        public bool Put { get; set; }
        public bool Patch { get; set; }
        public bool Delete { get; set; }
        [Column("PermissionGroupE920TableId")]
        public Guid PermissionGroupE920tableId { get; set; }
        [Column("E920TableFieldId")]
        public Guid E920tableFieldId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        [ForeignKey(nameof(E920tableFieldId))]
        [InverseProperty(nameof(E920tableFields.PermissionGroupE920tableFields))]
        public virtual E920tableFields E920tableField { get; set; }
        [ForeignKey(nameof(PermissionGroupE920tableId))]
        [InverseProperty(nameof(PermissionGroupE920tables.PermissionGroupE920tableFields))]
        public virtual PermissionGroupE920tables PermissionGroupE920table { get; set; }
    }
}