// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    [Table("PermissionGroupE920Tables")]
    public partial class PermissionGroupE920tables
    {
        public PermissionGroupE920tables()
        {
            PermissionGroupE920tableFields = new HashSet<PermissionGroupE920tableFields>();
        }

        [Key]
        public Guid Id { get; set; }
        public bool AccessGet { get; set; }
        public bool AccessPatch { get; set; }
        public bool AccessPost { get; set; }
        public bool AccessPut { get; set; }
        public bool AccessDelete { get; set; }
        public Guid PermissionGroupId { get; set; }
        [Column("E920TableId")]
        public Guid E920tableId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        [ForeignKey(nameof(E920tableId))]
        [InverseProperty(nameof(E920tables.PermissionGroupE920tables))]
        public virtual E920tables E920table { get; set; }
        [ForeignKey(nameof(PermissionGroupId))]
        [InverseProperty("PermissionGroupE920tables")]
        public virtual PermissionGroup PermissionGroup { get; set; }
        [InverseProperty("PermissionGroupE920table")]
        public virtual ICollection<PermissionGroupE920tableFields> PermissionGroupE920tableFields { get; set; }
    }
}