// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EFSecurity.Models
{
    public partial class RequestedSystemDetail
    {
        public RequestedSystemDetail()
        {
            ApplicationRequests = new HashSet<ApplicationRequest>();
        }

        [Key]
        public Guid Id { get; set; }
        public string AitrNumber { get; set; }
        public DateTime AtoAuthorizationDate { get; set; }
        public DateTime AtoExpirationDate { get; set; }
        public int DitprNumber { get; set; }
        [Column("eMassId")]
        public int EMassId { get; set; }
        public DateTime PiaApprovalDate { get; set; }
        public DateTime PiaReviewDate { get; set; }
        public string SornId { get; set; }
        public DateTime SornReviewDate { get; set; }
        public string SystemAcronym { get; set; }
        public string SystemName { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? DeletedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }

        [InverseProperty(nameof(ApplicationRequest.RequestedSystemDetails))]
        public virtual ICollection<ApplicationRequest> ApplicationRequests { get; set; }
    }
}